package org.gluu.oxtrust.api.oxtrust;

import org.gluu.oxtrust.api.configuration.oxtrust.OxTrustConfig;
import org.gluu.oxtrust.api.configuration.oxtrust.ScimPropertiesApi;
import org.xdi.config.oxtrust.AppConfiguration;
import org.xdi.config.oxtrust.ScimProperties;

import static org.gluu.oxtrust.service.config.oxtrust.OxTrustConfigurationService.HIDDEN_PASSWORD;

class OxTrustConfigDtoAssembly {

    OxTrustConfig toDto(AppConfiguration appConfiguration) {
        OxTrustConfig oxTrustConfig = new OxTrustConfig();
        oxTrustConfig.setBaseDN(appConfiguration.getBaseDN());
        oxTrustConfig.setOrgInum(appConfiguration.getOrgInum());
        oxTrustConfig.setOrgIname(appConfiguration.getOrgIname());
        oxTrustConfig.setOrgSupportEmail(appConfiguration.getOrgSupportEmail());
        oxTrustConfig.setApplianceInum(appConfiguration.getApplianceInum());
        oxTrustConfig.setApplianceUrl(appConfiguration.getApplianceUrl());
        oxTrustConfig.setBaseEndpoint(appConfiguration.getBaseEndpoint());
        oxTrustConfig.setPersonObjectClassTypes(appConfiguration.getPersonObjectClassTypes());
        oxTrustConfig.setPersonCustomObjectClass(appConfiguration.getPersonCustomObjectClass());
        oxTrustConfig.setPersonObjectClassDisplayNames(appConfiguration.getPersonObjectClassDisplayNames());
        oxTrustConfig.setContactObjectClassTypes(appConfiguration.getContactObjectClassTypes());
        oxTrustConfig.setContactObjectClassDisplayNames(appConfiguration.getContactObjectClassDisplayNames());
        oxTrustConfig.setPhotoRepositoryRootDir(appConfiguration.getPhotoRepositoryRootDir());
        oxTrustConfig.setPhotoRepositoryThumbWidth(appConfiguration.getPhotoRepositoryThumbWidth());
        oxTrustConfig.setPhotoRepositoryThumbHeight(appConfiguration.getPhotoRepositoryThumbHeight());
        oxTrustConfig.setPhotoRepositoryCountLeveles(appConfiguration.getPhotoRepositoryCountLeveles());
        oxTrustConfig.setPhotoRepositoryCountFoldersPerLevel(appConfiguration.getPhotoRepositoryCountFoldersPerLevel());
        oxTrustConfig.setLdifStore(appConfiguration.getLdifStore());
        oxTrustConfig.setUpdateApplianceStatus(appConfiguration.isUpdateApplianceStatus());
        oxTrustConfig.setSvnConfigurationStoreRoot(appConfiguration.getSvnConfigurationStoreRoot());
        oxTrustConfig.setKeystorePath(appConfiguration.getKeystorePath());
        oxTrustConfig.setAllowPersonModification(appConfiguration.isAllowPersonModification());
        oxTrustConfig.setIdpUrl(appConfiguration.getIdpUrl());
        oxTrustConfig.setVelocityLog(appConfiguration.getVelocityLog());
        oxTrustConfig.setSpMetadataPath(appConfiguration.getSpMetadataPath());
        oxTrustConfig.setLogoLocation(appConfiguration.getLogoLocation());
        oxTrustConfig.setIdpSecurityKey(appConfiguration.getIdpSecurityKey());
        oxTrustConfig.setIdpSecurityCert(appConfiguration.getIdpSecurityCert());
        oxTrustConfig.setGluuSpAttributes(appConfiguration.getGluuSpAttributes());
        oxTrustConfig.setConfigGeneration(appConfiguration.isConfigGeneration());
        oxTrustConfig.setIdpLdapProtocol(appConfiguration.getIdpLdapProtocol());
        oxTrustConfig.setIdpLdapServer(appConfiguration.getIdpLdapServer());
        oxTrustConfig.setIdpBindDn(appConfiguration.getIdpBindDn());
        oxTrustConfig.setIdpUserFields(appConfiguration.getIdpUserFields());
        oxTrustConfig.setGluuSpCert(appConfiguration.getGluuSpCert());
        oxTrustConfig.setShibboleth3FederationRootDir(appConfiguration.getShibboleth3FederationRootDir());
        oxTrustConfig.setCaCertsLocation(appConfiguration.getCaCertsLocation());
        oxTrustConfig.setTempCertDir(appConfiguration.getTempCertDir());
        oxTrustConfig.setCertDir(appConfiguration.getCertDir());
        oxTrustConfig.setServicesRestartTrigger(appConfiguration.getServicesRestartTrigger());
        oxTrustConfig.setPersistSVN(appConfiguration.isPersistSVN());
        oxTrustConfig.setOxAuthSectorIdentifierUrl(appConfiguration.getOxAuthSectorIdentifierUrl());
        oxTrustConfig.setOxAuthClientId(appConfiguration.getOxAuthClientId());
        oxTrustConfig.setOxAuthClientScope(appConfiguration.getOxAuthClientScope());
        oxTrustConfig.setLoginRedirectUrl(appConfiguration.getLoginRedirectUrl());
        oxTrustConfig.setLogoutRedirectUrl(appConfiguration.getLogoutRedirectUrl());
        oxTrustConfig.setClusteredInums(appConfiguration.getClusteredInums());
        oxTrustConfig.setClientAssociationAttribute(appConfiguration.getClientAssociationAttribute());
        oxTrustConfig.setOxAuthIssuer(appConfiguration.getOxAuthIssuer());
        oxTrustConfig.setIgnoreValidation(appConfiguration.isIgnoreValidation());
        oxTrustConfig.setUmaIssuer(appConfiguration.getUmaIssuer());
        oxTrustConfig.setScimUmaClientId(appConfiguration.getScimUmaClientId());
        oxTrustConfig.setScimUmaClientKeyId(appConfiguration.getScimUmaClientKeyId());
        oxTrustConfig.setScimUmaResourceId(appConfiguration.getScimUmaResourceId());
        oxTrustConfig.setScimUmaScope(appConfiguration.getScimUmaScope());
        oxTrustConfig.setScimUmaClientKeyStoreFile(appConfiguration.getScimUmaClientKeyStoreFile());
        oxTrustConfig.setScimUmaClientKeyStorePassword(appConfiguration.getScimUmaClientKeyStorePassword());
        oxTrustConfig.setPassportUmaClientId(appConfiguration.getPassportUmaClientId());
        oxTrustConfig.setPassportUmaClientKeyId(appConfiguration.getPassportUmaClientKeyId());
        oxTrustConfig.setPassportUmaResourceId(appConfiguration.getPassportUmaResourceId());
        oxTrustConfig.setPassportUmaScope(appConfiguration.getPassportUmaScope());
        oxTrustConfig.setPassportUmaClientKeyStoreFile(appConfiguration.getPassportUmaClientKeyStoreFile());
        oxTrustConfig.setPassportUmaClientKeyStorePassword(appConfiguration.getPassportUmaClientKeyStorePassword());
        oxTrustConfig.setApiUmaClientId(appConfiguration.getApiUmaClientId());
        oxTrustConfig.setApiUmaClientKeyId(appConfiguration.getApiUmaClientKeyId());
        oxTrustConfig.setApiUmaResourceId(appConfiguration.getApiUmaResourceId());
        oxTrustConfig.setApiUmaScope(appConfiguration.getApiUmaScope());
        oxTrustConfig.setApiUmaClientKeyStoreFile(appConfiguration.getApiUmaClientKeyStoreFile());
        oxTrustConfig.setApiUmaClientKeyStorePassword(appConfiguration.getApiUmaClientKeyStorePassword());
        oxTrustConfig.setCssLocation(appConfiguration.getCssLocation());
        oxTrustConfig.setJsLocation(appConfiguration.getJsLocation());
        oxTrustConfig.setRecaptchaSiteKey(appConfiguration.getRecaptchaSiteKey());
        oxTrustConfig.setRecaptchaSecretKey(appConfiguration.getRecaptchaSecretKey());
        oxTrustConfig.setScimTestMode(appConfiguration.isScimTestMode());
        oxTrustConfig.setRptConnectionPoolUseConnectionPooling(appConfiguration.isRptConnectionPoolUseConnectionPooling());
        oxTrustConfig.setRptConnectionPoolMaxTotal(appConfiguration.getRptConnectionPoolMaxTotal());
        oxTrustConfig.setRptConnectionPoolDefaultMaxPerRoute(appConfiguration.getRptConnectionPoolDefaultMaxPerRoute());
        oxTrustConfig.setRptConnectionPoolValidateAfterInactivity(appConfiguration.getRptConnectionPoolValidateAfterInactivity());
        oxTrustConfig.setRptConnectionPoolCustomKeepAliveTimeout(appConfiguration.getRptConnectionPoolCustomKeepAliveTimeout());
        oxTrustConfig.setOxIncommonFlag(appConfiguration.isOxIncommonFlag());
        oxTrustConfig.setClientWhiteList(appConfiguration.getClientWhiteList());
        oxTrustConfig.setClientBlackList(appConfiguration.getClientBlackList());
        oxTrustConfig.setLoggingLevel(appConfiguration.getLoggingLevel());
        oxTrustConfig.setShibbolethVersion(appConfiguration.getShibbolethVersion());
        oxTrustConfig.setShibboleth3IdpRootDir(appConfiguration.getShibboleth3IdpRootDir());
        oxTrustConfig.setShibboleth3SpConfDir(appConfiguration.getShibboleth3SpConfDir());
        oxTrustConfig.setOrganizationName(appConfiguration.getOrganizationName());
        oxTrustConfig.setIdp3SigningCert(appConfiguration.getIdp3SigningCert());
        oxTrustConfig.setIdp3EncryptionCert(appConfiguration.getIdp3EncryptionCert());
        oxTrustConfig.setMetricReporterInterval(appConfiguration.getMetricReporterInterval());
        oxTrustConfig.setScimProperties(scimProperties(appConfiguration));

        oxTrustConfig.setSvnConfigurationStorePassword(HIDDEN_PASSWORD);
        oxTrustConfig.setKeystorePassword(HIDDEN_PASSWORD);
        oxTrustConfig.setIdpSecurityKeyPassword(HIDDEN_PASSWORD);
        oxTrustConfig.setIdpBindPassword(HIDDEN_PASSWORD);
        oxTrustConfig.setCaCertsPassphrase(HIDDEN_PASSWORD);
        oxTrustConfig.setOxAuthClientPassword(HIDDEN_PASSWORD);

        return oxTrustConfig;
    }

    private ScimPropertiesApi scimProperties(AppConfiguration appConfiguration) {
        ScimPropertiesApi scimPropertiesApi = new ScimPropertiesApi();
        scimPropertiesApi.setMaxCount(appConfiguration.getScimProperties().getMaxCount());
        return scimPropertiesApi;
    }

    AppConfiguration fromDto(OxTrustConfig oxTrustConfig) {
        AppConfiguration appConfiguration= new AppConfiguration();
        appConfiguration.setScimProperties(scimProperties(oxTrustConfig));
        appConfiguration.setOxIncommonFlag(oxTrustConfig.isOxIncommonFlag());
        appConfiguration.setBaseDN(oxTrustConfig.getBaseDN());
        appConfiguration.setOrgInum(oxTrustConfig.getOrgInum());
        appConfiguration.setOrgIname(oxTrustConfig.getOrgIname());
        appConfiguration.setOrgSupportEmail(oxTrustConfig.getOrgSupportEmail());
        appConfiguration.setApplianceInum(oxTrustConfig.getApplianceInum());
        appConfiguration.setApplianceUrl(oxTrustConfig.getApplianceUrl());
        appConfiguration.setBaseEndpoint(oxTrustConfig.getBaseEndpoint());
        appConfiguration.setPersonObjectClassTypes(oxTrustConfig.getPersonObjectClassTypes());
        appConfiguration.setPersonCustomObjectClass(oxTrustConfig.getPersonCustomObjectClass());
        appConfiguration.setPersonObjectClassDisplayNames(oxTrustConfig.getPersonObjectClassDisplayNames());
        appConfiguration.setContactObjectClassTypes(oxTrustConfig.getContactObjectClassTypes());
        appConfiguration.setContactObjectClassDisplayNames(oxTrustConfig.getContactObjectClassDisplayNames());
        appConfiguration.setPhotoRepositoryRootDir(oxTrustConfig.getPhotoRepositoryRootDir());
        appConfiguration.setPhotoRepositoryThumbWidth(oxTrustConfig.getPhotoRepositoryThumbWidth());
        appConfiguration.setPhotoRepositoryThumbHeight(oxTrustConfig.getPhotoRepositoryThumbHeight());
        appConfiguration.setPhotoRepositoryCountLeveles(oxTrustConfig.getPhotoRepositoryCountLeveles());
        appConfiguration.setPhotoRepositoryCountFoldersPerLevel(oxTrustConfig.getPhotoRepositoryCountFoldersPerLevel());
        appConfiguration.setLdifStore(oxTrustConfig.getLdifStore());
        appConfiguration.setUpdateApplianceStatus(oxTrustConfig.isUpdateApplianceStatus());
        appConfiguration.setSvnConfigurationStoreRoot(oxTrustConfig.getSvnConfigurationStoreRoot());
        appConfiguration.setSvnConfigurationStorePassword(oxTrustConfig.getSvnConfigurationStorePassword());
        appConfiguration.setKeystorePath(oxTrustConfig.getKeystorePath());
        appConfiguration.setKeystorePassword(oxTrustConfig.getKeystorePassword());
        appConfiguration.setAllowPersonModification(oxTrustConfig.isAllowPersonModification());
        appConfiguration.setIdpUrl(oxTrustConfig.getIdpUrl());
        appConfiguration.setVelocityLog(oxTrustConfig.getVelocityLog());
        appConfiguration.setSpMetadataPath(oxTrustConfig.getSpMetadataPath());
        appConfiguration.setLogoLocation(oxTrustConfig.getLogoLocation());
        appConfiguration.setIdpSecurityKey(oxTrustConfig.getIdpSecurityKey());
        appConfiguration.setIdpSecurityKeyPassword(oxTrustConfig.getIdpSecurityKeyPassword());
        appConfiguration.setIdpSecurityCert(oxTrustConfig.getIdpSecurityCert());
        appConfiguration.setGluuSpAttributes(oxTrustConfig.getGluuSpAttributes());
        appConfiguration.setConfigGeneration(oxTrustConfig.isConfigGeneration());
        appConfiguration.setIdpLdapProtocol(oxTrustConfig.getIdpLdapProtocol());
        appConfiguration.setIdpLdapServer(oxTrustConfig.getIdpLdapServer());
        appConfiguration.setIdpBindDn(oxTrustConfig.getIdpBindDn());
        appConfiguration.setIdpBindPassword(oxTrustConfig.getIdpBindPassword());
        appConfiguration.setIdpUserFields(oxTrustConfig.getIdpUserFields());
        appConfiguration.setGluuSpCert(oxTrustConfig.getGluuSpCert());
        appConfiguration.setShibboleth3FederationRootDir(oxTrustConfig.getShibboleth3FederationRootDir());
        appConfiguration.setCaCertsLocation(oxTrustConfig.getCaCertsLocation());
        appConfiguration.setCaCertsPassphrase(oxTrustConfig.getCaCertsPassphrase());
        appConfiguration.setTempCertDir(oxTrustConfig.getTempCertDir());
        appConfiguration.setCertDir(oxTrustConfig.getCertDir());
        appConfiguration.setServicesRestartTrigger(oxTrustConfig.getServicesRestartTrigger());
        appConfiguration.setPersistSVN(oxTrustConfig.isPersistSVN());
        appConfiguration.setOxAuthSectorIdentifierUrl(oxTrustConfig.getOxAuthSectorIdentifierUrl());
        appConfiguration.setOxAuthClientId(oxTrustConfig.getOxAuthClientId());
        appConfiguration.setOxAuthClientPassword(oxTrustConfig.getOxAuthClientPassword());
        appConfiguration.setOxAuthClientScope(oxTrustConfig.getOxAuthClientScope());
        appConfiguration.setLoginRedirectUrl(oxTrustConfig.getLoginRedirectUrl());
        appConfiguration.setLogoutRedirectUrl(oxTrustConfig.getLogoutRedirectUrl());
        appConfiguration.setClusteredInums(oxTrustConfig.getClusteredInums());
        appConfiguration.setClientAssociationAttribute(oxTrustConfig.getClientAssociationAttribute());
        appConfiguration.setOxAuthIssuer(oxTrustConfig.getOxAuthIssuer());
        appConfiguration.setIgnoreValidation(oxTrustConfig.isIgnoreValidation());
        appConfiguration.setUmaIssuer(oxTrustConfig.getUmaIssuer());
        appConfiguration.setScimUmaClientId(oxTrustConfig.getScimUmaClientId());
        appConfiguration.setScimUmaClientKeyId(oxTrustConfig.getScimUmaClientKeyId());
        appConfiguration.setScimUmaResourceId(oxTrustConfig.getScimUmaResourceId());
        appConfiguration.setScimUmaScope(oxTrustConfig.getScimUmaScope());
        appConfiguration.setScimUmaClientKeyStoreFile(oxTrustConfig.getScimUmaClientKeyStoreFile());
        appConfiguration.setScimUmaClientKeyStorePassword(oxTrustConfig.getScimUmaClientKeyStorePassword());
        appConfiguration.setPassportUmaClientId(oxTrustConfig.getPassportUmaClientId());
        appConfiguration.setPassportUmaClientKeyId(oxTrustConfig.getPassportUmaClientKeyId());
        appConfiguration.setPassportUmaResourceId(oxTrustConfig.getPassportUmaResourceId());
        appConfiguration.setPassportUmaScope(oxTrustConfig.getPassportUmaScope());
        appConfiguration.setPassportUmaClientKeyStoreFile(oxTrustConfig.getPassportUmaClientKeyStoreFile());
        appConfiguration.setPassportUmaClientKeyStorePassword(oxTrustConfig.getPassportUmaClientKeyStorePassword());
        appConfiguration.setCssLocation(oxTrustConfig.getCssLocation());
        appConfiguration.setJsLocation(oxTrustConfig.getJsLocation());
        appConfiguration.setRecaptchaSiteKey(oxTrustConfig.getRecaptchaSiteKey());
        appConfiguration.setRecaptchaSecretKey(oxTrustConfig.getRecaptchaSecretKey());
        appConfiguration.setScimTestMode(oxTrustConfig.isScimTestMode());
        appConfiguration.setRptConnectionPoolUseConnectionPooling(oxTrustConfig.isRptConnectionPoolUseConnectionPooling());
        appConfiguration.setRptConnectionPoolMaxTotal(oxTrustConfig.getRptConnectionPoolMaxTotal());
        appConfiguration.setRptConnectionPoolDefaultMaxPerRoute(oxTrustConfig.getRptConnectionPoolDefaultMaxPerRoute());
        appConfiguration.setRptConnectionPoolValidateAfterInactivity(oxTrustConfig.getRptConnectionPoolValidateAfterInactivity());
        appConfiguration.setRptConnectionPoolCustomKeepAliveTimeout(oxTrustConfig.getRptConnectionPoolCustomKeepAliveTimeout());
        appConfiguration.setShibbolethVersion(oxTrustConfig.getShibbolethVersion());
        appConfiguration.setShibboleth3IdpRootDir(oxTrustConfig.getShibboleth3IdpRootDir());
        appConfiguration.setShibboleth3SpConfDir(oxTrustConfig.getShibboleth3SpConfDir());
        appConfiguration.setOrganizationName(oxTrustConfig.getOrganizationName());
        appConfiguration.setIdp3SigningCert(oxTrustConfig.getIdp3SigningCert());
        appConfiguration.setIdp3EncryptionCert(oxTrustConfig.getIdp3EncryptionCert());
        appConfiguration.setClientWhiteList(oxTrustConfig.getClientWhiteList());
        appConfiguration.setClientBlackList(oxTrustConfig.getClientBlackList());
        appConfiguration.setLoggingLevel(oxTrustConfig.getLoggingLevel());
        appConfiguration.setMetricReporterInterval(oxTrustConfig.getMetricReporterInterval());
        appConfiguration.setApiUmaClientId(oxTrustConfig.getApiUmaClientId());
        appConfiguration.setApiUmaClientKeyId(oxTrustConfig.getApiUmaClientKeyId());
        appConfiguration.setApiUmaResourceId(oxTrustConfig.getApiUmaResourceId());
        appConfiguration.setApiUmaScope(oxTrustConfig.getApiUmaScope());
        appConfiguration.setApiUmaClientKeyStoreFile(oxTrustConfig.getApiUmaClientKeyStoreFile());
        appConfiguration.setApiUmaClientKeyStorePassword(oxTrustConfig.getApiUmaClientKeyStorePassword());
        return appConfiguration;
    }

    private ScimProperties scimProperties(OxTrustConfig oxTrustConfig) {
        ScimProperties scimProperties = new ScimProperties();
        scimProperties.setMaxCount(oxTrustConfig.getScimProperties().getMaxCount());
        return scimProperties;
    }

}
