pipeline {
    agent master
    tools {
        maven 'apache-maven-3.3.9' 
    }
    stages {
        stage('Cloning') {
            steps {
                echo 'Cloning oxTrust project..'
                sh "git https://github.com/GluuFederation/oxTrust.git"
                sh "cd oxTrust/qa"
                echo 'Done..'
            }
        }
        stage('BEFORE') {
            steps {
                echo 'Preparing for test'
            }
        }
        stage('QA TEST') {
            steps {
                echo 'Testing..'
                sh "cd oxTrust/oxtrust-qa"
                sh "mvn test -Dcucumber.options="--tags @gluuQA""
            }
        }
        stage('AFTER') {
            steps {
                echo 'Test done, sending notification'
            }
        }
    }
}